### ISSUE TITLE
comparision to twine

### ISSUE THREAD

**Issue by gaborbernat** [jwodder/check-wheel-contents#1]
Hello,

How is this different than ``twine check``, should this be integrated into ``twine check``?

**Comment by jwodder** [comment]
`twine check` just checks whether your long description will render properly.  `check-wheel-contents` checks that your wheel doesn't contain any `*.pyc` files; checks it doesn't contain any common toplevel names (`tests`, `docs`, `src`, etc.); checks that all toplevel objects are directories, Python modules, and/or `*.pth` files; optionally checks that the file tree in the wheel matches a local file tree; and other things (see the README for the full list).  I wouldn't be opposed to having this integrated into `twine check`, but I don't know whether that's something the `twine` people would be interested in anyway.  Some of the checks are a bit too opinion-based or conditional for something like `twine`, though, like the check for duplicate files (perfectly OK, just sometimes a sign something went wrong) or the check for modules without importable names (which can legitimately occur with alembic revision files whose hash starts with a digit).

**Comment by gaborbernat** [comment]
Created issue upstream to check how much of this would be good to have there 😊
