### ISSUE TITLE
Run tests on Windows

### ISSUE THREAD

**Issue by domdfcoding** [jwodder/check-wheel-contents#22]
Following on from #4

Adding Windows to the text matrix itself isn't too hard (see https://github.com/domdfcoding/check-wheel-contents/commit/d1840588f3277aed14848e349949eafe2540226f)

The tricky bit is the tests. Some tests are expecting the output to use POSIX-style path separators, but by default on Windows the paths are being printed with backslashes. The way I usually solve this is to always print paths with forward slashes, even on Windows. Windows of course can understand both forward and back slashes.

I think I've got everything working in my [windows](https://github.com/domdfcoding/check-wheel-contents/tree/windows) branch. See https://github.com/domdfcoding/check-wheel-contents/commit/4164f5d145342734550c62fcba458c40e7243fa1 for the changes to the program and https://github.com/domdfcoding/check-wheel-contents/commit/674e37cac69150457b186940c2e726c919ce3ac3 for the tests.

Happy to submit this as a PR.

**Comment by jwodder** [comment]
I managed to get the tests to pass on Windows a different way, by editing the tests to stringify `Path` objects; see 2634a7d5a3937b087d6c3c3b0ffa88f7a5cb5dd9.  Thanks for bringing this to my attention.

**Comment by domdfcoding** [comment]
Fab 👍
