### ISSUE TITLE
Support for pydantic 2.0

### ISSUE THREAD

**Issue by jonyscathe** [jwodder/check-wheel-contents#23]
Hey,
Is support for pydantic 2.0 likely to come along at some point?

Not sure how big a change it would be...
I know that this would need to change: https://github.com/jwodder/check-wheel-contents/blob/master/src/check_wheel_contents/config.py#L58 as 'allow_population_by_field_name' has been renamed to 'populate_by_name'.

Though given the amount of changes in pydantic I am guessing there would be more than just that.

**Comment by jonyscathe** [comment]
FYI, at least in a couple of my projects.
If 'allow_population_by_field_name' is renamed to 'populate_by_name' and `from pydantic import ...` is changed to `from pydantic.v1 import ...` then it at least works with pydantic v2.

Obviously this is not a good solution... But it at least solves the conflict we were having in a project where we want to run check-wheel-contents, but the project has already updated to pydantic v2 and due to our slightly flawed project setup our dev dependencies can't clash with our project's actual dependencies...

**Comment by jwodder** [comment]
check-wheel-contents v0.5.0 is out now with support for pydantic 2.0.
