### ISSUE TITLE
W005 should respect toplevel

### ISSUE THREAD

**Issue by henryiii** [jwodder/check-wheel-contents#24]
Currently, the list of directory names is hardcoded in W005:

https://github.com/jwodder/check-wheel-contents/blob/5d8f759d5fbd80e1e1b24a86ff5401c1c793d8a8/src/check_wheel_contents/checker.py#L196C27-L196C39

However, if you _are_ one of these packages (currently running into this with `build`), you can't just disable the directory that is okay. To fix this, `toplevel` should be subtracted from this list, then setting `toplevel=["build"]` would allow build to still get the benefit of the rest of this check. 

Ref: https://github.com/pypa/build/pull/669

**Comment by jwodder** [comment]
This is now possible with `check-wheel-contents` v0.6.0, just released.
