### ISSUE TITLE
W004 fails Django migrations directories

### ISSUE THREAD

**Issue by hmpf** [jwodder/check-wheel-contents#5]
By default, a django app has a directory with the name `migrations`. Inside is an `__init__.py`-file, but the names of the files generated by the database migration system are not valid identifiers as they start with a number, for sorting.

`filetree.File.is_valid_module_path()` fails, which triggers W0004.

You might want to document that W004 needs to be turned off for Django projects that use migrations (and how to do it). (I do not recommend weighing in on whether that directory should have an `__init__.py` or whether migrations should be in a wheel at all, you might get stuck.)

(An extra check to ensure that the migrations-directory is *there* would be nice though as it is perfectly possible to configure your setup.cfg wrong in this instance. Ditto app-templates, which are data that needs to exist in the source code tree. Static-file directories can easily be renamed so _that_ one is probably not worth the effort.)

**Comment by jwodder** [comment]
I've added a note to the README about this.  Ignoring the check can be done with the `--ignore` option/`ignore` config file setting, but this will disable the check for the entire wheel.   I have not yet implemented ignoring checks only for specific files.

Checking that the migrations directory is present in the wheel can be done with the W101 check, which is enabled when the `--package` or `--src-dir` option is set.
